### ISSUE TITLE
Choix des combos à l'intérieur des entraînements

### ISSUE THREAD

**Issue by PaulBarbieux** [PaulBarbieux/shadow#10]
Quand on choisit un entraînement, possibilité de voir les combos et d'en décocher.

**Comment by PaulBarbieux** [comment]
C'est programmé avec le package 8adb6ecb80bc0e1921650e44100657dbc2744f33.
@ClaudeHanssens Tu peux voir le résultat sur mon site test : http://extrapaul.be/shadow/

**Comment by ClaudeHanssens** [comment]
Publié. Nettement mieux.
Une demande d'amélioration:
Actuellement, quand on veut voir les combos d'un entrainement, le fait de cliquer sur l'entrainement coche toutes les combos directement.
Donc pour sélectionner 2-3 combos, il faut décocher toutes les autres.
L'idéal:
Quand on clique sur la coche, on coche/décoche toutes les combos de l'entrainement.
Quand on clique sur le libellé, on affiche les combos sans les cocher ou les décocher.

**Comment by PaulBarbieux** [comment]
Je m'attendais à cette demande.
Mais c'est complexe et j'ai préféré déjà publié tel-quel.
Je vais en faire une autre demande et fermer celle-ci.
