### ISSUE TITLE
Arrêt d'un entrainement - amélioration

### ISSUE THREAD

**Issue by ClaudeHanssens** [PaulBarbieux/shadow#12]
On peut arrêter un entrainement en cours en cliquant sur l'image ou en appuyant sur la Space bar quand on est sur la 2ème image d'une combo.
Quand on agit quand l'image de base est affichée, cela ne fonctionne pas.
C'est un peu gênant.
L'idéal est que l'on puisse arrêter l'entrainement même quand l'image de base est affichée.

**Comment by PaulBarbieux** [comment]
Corrigé : d93c7fe6bde350e673abe33ec1e6216a68bb6715
