### ISSUE TITLE
Durée de l'action

### ISSUE THREAD

**Issue by ClaudeHanssens** [PaulBarbieux/shadow#14]
Suite au commentaire d'un pratiquant d très haut niveau:
  * ajouter l'option 10 sec dans la liste "Durée de l'action".
L'idée est de permettre une pratique lente de la défense.

**Comment by PaulBarbieux** [comment]
OK. Ce sera presque tu Taichi !
;-)

**Comment by PaulBarbieux** [comment]
@ClaudeHanssens  La durée de l'action va déjà jusqu'à 8 secondes. 10 secondes ne me semble pas faire une différence.
Deux propositions :
- Remplacer 8 secondes par 10 (dommage pour la suite de Fibonacci !)
- Augmenter le temps de pause qui est actuellement max 2 secondes.

**Comment by ClaudeHanssens** [comment]
Je viens de vérifier le temps pour l'action.
Sur mon PC, quand je choisis 8 sec, le temps réel est de 6-7 sec environ. Même en mettant le temps de pause à 0 sec.
Il faudrait en premier lieu vérifier cela.

**Comment by PaulBarbieux** [comment]
Le timing était mal calculé avec le fondu entre les images : réparé, le chrono à l'air bon.

L'arrêt par click sur la première image ne fonctionnait pas : c'est réparé aussi.

Publié : 3ceca1ab7f381624be4ff218f3fcefa6feda221d

**Comment by ClaudeHanssens** [comment]
Le timing corrigé rajoute le temps manquant (1-2 sec). L'option 10 sec n'est plus nécessaire.
On peut clôturer l'issue.
