### ISSUE TITLE
Tri des entrainements

### ISSUE THREAD

**Issue by ClaudeHanssens** [PaulBarbieux/shadow#16]
Je reviens avec cette demande.
Il faudrait ajouter un champ "Ordre de tri" et que les entrainements apparaissent en suivant cet ordre dans le menu.
Actuellement, le tri se fait sur la clé. Cela est compliqué pour avoir l'ordre désiré.

**Comment by PaulBarbieux** [comment]
Résolu : 0920a0654d43eca7803a78faeb1263c723ea6649
