### ISSUE TITLE
Admin - Entrainement - Images sous IE

### ISSUE THREAD

**Issue by ClaudeHanssens** [PaulBarbieux/shadow#18]
Dans la partie Administration, Section Entrainements, quand je regarde avec Internet Explorer 11, les images sont mal dimensionnées.
Je suis conscient que IE est en fin de vie, mais il faudrait vérifier si cela ne peut pas se reproduire sur un autre logiciel.
Peut-être imposer une taille d'ilmage ??
![ShadowTraining-Admin-Entrainement](https://user-images.githubusercontent.com/59171757/75624151-0a19f100-5bb2-11ea-9c9d-fcf06cfe2d29.png)

**Comment by PaulBarbieux** [comment]
En effet, il ne faut pas laisser ainsi. Je crois avoir déjà rencontré ce problème.

**Comment by PaulBarbieux** [comment]
Les vinettes ont maintenant une taille fixe, plus petite : 6225f4ecaf8af08cc5c933346f3c3cc4fce16912
