### ISSUE TITLE
Créer un page d'accueil

### ISSUE THREAD

**Issue by ClaudeHanssens** [PaulBarbieux/shadow#2]
Créer une page d'accueil présentant le site:

- Mode d'emploi simple.

**Comment by PaulBarbieux** [comment]
@ClaudeHanssens  Avant de publier ici, je voudrais que tu regardes ma proposition de texte. J'ai publié la page d'acceuil sur mon site test : http://www.extrapaul.be/shadow/

Pour la photo c'est temporaire : j'attends ta proposition d'image.

**Comment by ClaudeHanssens** [comment]
Pour moi, le texte est bon.
Je changerai:
* _est montrée et vous réagissez_ : supprimer la virgule.
* _Par exemple: les attaques au couteau_: ajouter double point
* _ordre aléatoire.
 A vous de réagir !_

La photo est OK pour moi.

Merci.

**Comment by PaulBarbieux** [comment]
Corrections publiées : commit b11f07272b8672e2efde6944005d2e48dbe59121.

La page d'accueil sera relookées plus tard, peut-être fondue avec training.php : objet d'un issue séparé, à venir.
