### ISSUE TITLE
Modification de la DB

### ISSUE THREAD

**Issue by ClaudeHanssens** [PaulBarbieux/shadow#20]
J'aurais besoin des modifications suivantes à la DB:
Table trainings: id devient INTEGER avec NN CP IA U
Table training_combos: training_id devient INTEGER; training_id et combo_id deviennent CP

Il y aura peut-être des adaptations à faire dans l'interface d'administration.

**Comment by PaulBarbieux** [comment]
Techniquement ça devrait aller.

Par contre on va perdre en lisibilité dans les tables. Javais mis un id mémotechnique pour les trainings dans le but de s'y retrouver quand on doit manipuler les tables dans SQLite. Mais quand tous les écrans d'administration sont complets, on ne doit jamais chipoter dans la base de données, donc ta demande est dans la logique des choses.

Par contre attention : les id de trainings sont référencés dans la table presets (les enregistrements d'entraînements). J'aimerais éviter de devoir écrire un script qui va les mettre à jour : est-ce envisageable de vider cette table ? Car les données ne seront plus bonnes.

**Comment by ClaudeHanssens** [comment]
Comme discuté, actuellement, tous les trainig_id sont des chiffres.
J'ai fait manuellement sans soucis les modifications dans une copie de la DB.
Il ne faut donc pas prévoir de script de correction des données, uniquement ceux pour modifier les tables. Je peux même faire les modif manuellement s'il le faut.
Il te faut juste bien vérifier le code: training_id = quote( ...), etc

**Comment by PaulBarbieux** [comment]
Seul la page de gestion des entraînements est concernée par ce changement sur l'id : 799cb3c8638f117f5b34ec3c017fb00c82119da6

Je ne peux pas fournir un script pour modifier la base de données.
Il faut donc modifier l'id de la table trainings :
`"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE`
et de la table training_combos :
`"training_id"	INTEGER NOT NULL`

**Comment by ClaudeHanssens** [comment]
DB www.shadowtraiing.be modifiée. Code adapté mis en ligne.
