### ISSUE TITLE
Listage de répertoire

### ISSUE THREAD

**Issue by ClaudeHanssens** [PaulBarbieux/shadow#26]
Il était possible de lister le contenu d'un répertoire.
Je préfère éviter cela.
J'ai donc mis dans le répertoire racine le fichier .htaccess, contenant la ligne "Options -Indexes".
Il faut le rajouter sur GitHub pour synchroniser.
[htaccess.zip](https://github.com/PaulBarbieux/shadow/files/4503457/htaccess.zip)

**Comment by PaulBarbieux** [comment]
C'est une bonne idée.
Je ne connais pas grand chose à .htaccess : je le place à la racine du site, ou bien partout (tous les répertoires) ?

**Comment by ClaudeHanssens** [comment]
Il doit être placé dans le répertoire racine.
Il va s'appliquer à tous les répertoires en dessous.

**Comment by PaulBarbieux** [comment]
Publié : 270e9970d59d3f77881b5afa76b842b257fbab00

**Comment by PaulBarbieux** [comment]
Publié : 270e9970d59d3f77881b5afa76b842b257fbab00
