### ISSUE TITLE
Site bilingue français / anglais

### ISSUE THREAD

**Issue by PaulBarbieux** [PaulBarbieux/shadow#4]
Rendre le site bilingue français / anglais :

1. Détection de la langue par défaut sur base du navigateur.
2. Lien de changement de langue.
3. Traductions de l'intro, des explications, des paramètres.
4. Vérifier que les tables de la base de données permettent les textes anglais pour les combos et entraînements.

**Comment by PaulBarbieux** [comment]
Les tables SQL ne contiennent pas encore les colonnes pour l'anglais.
Il faut les leur ajouter avec le script suivant, à exécuter dans SQLite Browser :

```
ALTER TABLE combos ADD action_en TEXT;
ALTER TABLE combos ADD response_en TEXT;
ALTER TABLE trainings ADD title_en TEXT;
ALTER TABLE trainings ADD text_en TEXT;
```

**Comment by PaulBarbieux** [comment]
@ClaudeHannsens : Dans la discussion hier concernant les traductions, on oubliait le texte de page d'accueil. Sais-tu la traduire ?

**Comment by PaulBarbieux** [comment]
Site bilingue programmé : c23a9dfb9f9bdfbf7872cf7b1cdcd84a3e4ba051

Les textes de la page d'introduction sont délocalisées dans /content/intro_en.htm et intro_fr.htm. Le texte anglais doit donc être traduit en modifiant intro_en.htm avec un éditeur HTML.

config.php ne doit pas être récupéré : il est dans le commit parce que j'ai ajouté un mot clé pour tester.

L'interface d'administration n'est pas encore prête pour gérer les textes anglais.

**Comment by ClaudeHanssens** [comment]
Page d'accueil traduite en UK (pourrait être vérifiée par un anglophone pour être sûr).
Légère modif de la page d'accueil FR.
Les champs anglais des tables Combos et Trainings ont été complétés par copie des zones _fr: pour le moment, les textes sont en anglais dans les zones _fr.
[intro.zip](https://github.com/PaulBarbieux/shadow/files/4010552/intro.zip)
