### ISSUE TITLE
Bug: pas d'affichage de la page training.php

### ISSUE THREAD

**Issue by ClaudeHanssens** [PaulBarbieux/shadow#5]
Quand on clique sur le bouton "Lancez l'entrainement", on obtient une erreur http 500.

**Comment by PaulBarbieux** [comment]
Je n'arrive pas à reproduire cette erreur. Sur quelle site ça se passe ? Le mien ? http://www.extrapaul.be/shadow/training.php

**Comment by PaulBarbieux** [comment]
OK j'ai trouvé une erreur d'adressage.
Réparé, il faut juste reprendre training.php : 2099ffdee0257fb7fe3b25b9d227eba251c8aa1c
