### ISSUE TITLE
Présence dans Google Search

### ISSUE THREAD

**Issue by ClaudeHanssens** [PaulBarbieux/shadow#7]
J'ai travaillé sur la présence du site dans les résultats Google.
1) Enregistrement de l'URL shadowtraining.be dans la Google Search Console.
2) Création du fichier shadowtrainingsitemap.txt, placé dans \content et signalé dans la Google Search Console.
[shadowtrainingsitemap.txt](https://github.com/PaulBarbieux/shadow/files/4008315/shadowtrainingsitemap.txt)

=> ajouter le fichier dans la version GIT

3) Modification du fichier Content\config.php
define ('SITE_DESCRIPTION_FR', "Shadow Training: Entraînement de Krav Maga. Entraînez vos techniques de Krav Maga chez vous!");
define ('SITE_DESCRIPTION_EN', "Shadow Training: Training for Krav Maga. Train your Krav Maga techniques at home!");
define ('SITE_KEYWORDS_FR', "krav maga, shadow training");
define ('SITE_KEYWORDS_EN', "krav maga, shadow training");

PS: Les Keywords ne sont plus utilisés en SEO, mais juste pour être cohérent.

=> ajouter dans le fichier GIT

**Résultat:** 
Déjà quand on tape shadowtraining.be dans Google Search, on obtient un lien vers le site.

**Comment by PaulBarbieux** [comment]
J'ai modifié config.php et ajouté le txt.
Toutefois, ceci est normalement de l'ordre de la configuration personnalisée. Il y a en effet plusieurs manières de référencer un site, à charge du webmaster de le faire à sa convenance.
Mais ce code source est à l'image de ton site, donc ok.
Publié en même tant que le bug #8 : 3b7ad0015ea66d1ad8bf63458dbb91542b8e69c4
