### ISSUE TITLE
Bug: Admin Combos - images non affichées

### ISSUE THREAD

**Issue by ClaudeHanssens** [PaulBarbieux/shadow#8]
Dans Admin - Combos/Handguns
1) dans la combo "Handgun Threat with Push - Cross", l'image de fin n'est pas affichée.
2) dans la combo "Handgun Threat with Push - Direct", l'image de fin n'est pas affichée.
Quand on modifie les Combo, on voit bien le nom des images.
Quand on lance l'entrainement, on voit bien les images.
Le souci semble bien dans la page Admin - Combos.
Peut-être un problème de longueur de nom ???
Pas d'urgence.

**Comment by PaulBarbieux** [comment]
Le problème venait des noms de fichiers contenant des espaces.
C'est corrigé, publié dans un package reprenant ta proposition de référencement : 3b7ad0015ea66d1ad8bf63458dbb91542b8e69c4
